v = c(1,2,3,4,3,2,4,5,5)
cat("Original vector.\n")
cat(v,"\nIs this a factor :",is.factor(v))
cat("\n\nAfter making it factor :\n")
v = factor(v)
cat(v,"\nIs this a factor :",is.factor(v))
cat("\nLevels of factor of the said vector.\n")
cat(levels(factor(v)),"\n\n")
str(v)
cat("\nAfter adding one more level :\n")
levels(v) = c(levels(v),0)
str(v)