fact1 <- factor(c("Q","Y","M","J","J","H"))
fact2 <- factor(c("B","J","L","S","F","Z"))
cat("Factor1 : ")
print(fact1)
cat("\nFactor2 : ")
print(fact2)
cat("\nAfter concatenate factor becomes : ")
fact = factor(c(levels(fact1)[fact1],levels(fact2)[fact2]))
print(fact)